{{- $fullName := include "mrrobot-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mrrobot-api.labels" . | nindent 4 }}
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/mrrobot"
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}