apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-robot-deployment
  labels:
    app: mr-robot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mr-robot
  template:
    metadata:
      labels:
        app: mr-robot
    spec:
      containers:
        - name: mr-robot
          image: acrmrrobotdev.azurecr.io/mrrobot:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
