apiVersion: v1
kind: Service
metadata:
  labels:
    app: mr-robot
  name: mr-robot-api-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 5000
  selector:
    app: mr-robot
  type: LoadBalancer
